#!/usr/bin/env tsx
/*
 * init.ts — idempotent, OFFLINE scaffold + drift check for the Confluence
 * citation-cache mirror (plan 01c §11 Phase 0).
 *
 * WHY a script (not just inline): `/confluence-init` (Phase 1) needs the exact
 * same "stand up the skeleton, then on re-run report drift instead of
 * clobbering" behaviour that `/jira-init` has. Extracting it here removes the
 * duplication — the router runs this via
 * `node_modules/.bin/tsx scripts/confluence/init.ts` when present.
 *
 * Contract (load-bearing — this is the Phase-0 gate):
 *   - PURE / OFFLINE. Touches only confluence/ on disk. NO network, NO remote
 *     mutations, nothing pulled. Discovery is Rovo-first and happens in later
 *     phases; this only writes the local scaffold.
 *   - IDEMPOTENT. First run creates the skeleton. A second run COMPARES desired
 *     vs on-disk and prints a DRIFT REPORT rather than overwriting — the mirror
 *     of how /jira-init behaves.
 *   - Identity resolution is read from .claude/config/people.json directly by
 *     agents and commands. people.json IS the single source of truth
 *     (gitignored, regenerated by /jira-init).
 *   - TWO-TIMESTAMP invariant reserved: generatedAt (every reindex) !=
 *     lastSyncedAt (only a real pull). Established in the schema now; unused
 *     until Phase 3.
 *
 * The `now` timestamp is injected (arg / env) so the run is deterministic and
 * unit-testable; there is no Date.now() in the pure path.
 *
 *   Apply:     tsx scripts/confluence/init.ts [--now <iso>] [--root <dir>]
 *   Check:     tsx scripts/confluence/init.ts --check   (report drift, write nothing)
 *   Self-test: tsx scripts/confluence/init.ts --selftest
 */

import { writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

// ---- shapes -----------------------------------------------------------------

interface Drift {
  dirs: string[]; // missing dirs/files
  clean: boolean;
}

// ---- constants: the desired scaffold ---------------------------------------

const SUBDIRS = ['spaces', 'pages', 'blogposts', 'attachments'] as const;

// ---- IO-bound apply / check -------------------------------------------------

function computeDrift(root: string): Drift {
  const confRoot = join(root, 'confluence');
  const dirs: string[] = [];

  if (!existsSync(join(confRoot, '.manifest.json'))) dirs.push('confluence/.manifest.json');
  if (!existsSync(join(confRoot, 'manifest.schema.json'))) dirs.push('confluence/manifest.schema.json');
  for (const d of SUBDIRS) {
    if (!existsSync(join(confRoot, d))) dirs.push(`confluence/${d}/`);
    else if (!existsSync(join(confRoot, d, '.gitkeep'))) dirs.push(`confluence/${d}/.gitkeep`);
  }

  return { dirs, clean: dirs.length === 0 };
}

function apply(root: string): void {
  const confRoot = join(root, 'confluence');
  mkdirSync(confRoot, { recursive: true });
  for (const d of SUBDIRS) {
    const dir = join(confRoot, d);
    mkdirSync(dir, { recursive: true });
    const keep = join(dir, '.gitkeep');
    if (!existsSync(keep)) writeFileSync(keep, '');
  }
}

// ---- report -----------------------------------------------------------------

function printDrift(d: Drift): void {
  if (d.clean) {
    console.log('confluence init — CLEAN. Scaffold matches desired state; nothing to do.');
    return;
  }
  console.log('confluence init — DRIFT DETECTED (nothing written):');
  if (d.dirs.length) {
    console.log('\n  Missing scaffold:');
    for (const x of d.dirs) console.log(`    ${x}`);
  }
  console.log('\n  Re-run without --check to create missing dirs.');
}

// ---- self-test (pure — no IO) -----------------------------------------------

function selftest(): void {
  // Scaffold drift detection is IO-bound; verify the pure constant shape only.
  const expected = ['spaces', 'pages', 'blogposts', 'attachments'];
  assert(JSON.stringify([...SUBDIRS]) === JSON.stringify(expected), 'SUBDIRS shape');
  console.log('selftest: all assertions passed');
}

function assert(cond: boolean, msg: string): void {
  if (!cond) {
    console.error('selftest FAILED:', msg);
    process.exit(1);
  }
}

// ---- entry ------------------------------------------------------------------

function argVal(flag: string): string | undefined {
  const i = process.argv.indexOf(flag);
  if (i < 0) return undefined;
  return process.argv[i + 1] as string | undefined;
}

function main(): void {
  const root = argVal('--root') ?? process.cwd();
  // --now retained for CLI compat but unused now that no generatedAt is written
  void argVal('--now');

  if (process.argv.includes('--selftest')) return selftest();

  const drift = computeDrift(root);
  if (process.argv.includes('--check')) return printDrift(drift);

  // Apply mode: create anything missing, always print the drift summary.
  if (!drift.clean) apply(root);
  printDrift(computeDrift(root));
}

main();
