/**
 * {Entity} component template
 * Read @.claude/xxxx/component-library.md and ALWAYS check apps/web/src/components/
 * (Storybook library) before creating a new component — reuse before creating.
 * Use Context7 MCP for NextJS/React/TanStack/RHF/Zod implementation patterns.
 *
 * Replace {Entity} (PascalCase), {entity} (camelCase), {resources} (kebab/plural),
 * {ENTITY} (SCREAMING) with real names before use.
 */

'use client'; // Remove if no hooks/events needed (prefer RSC)

import { useState, useCallback } from 'react';
import Link from 'next/link';

// UI primitives live in the Storybook library — import the real ones you need.
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';

// React Query hooks are GENERATED by orval — never hand-write them.
// Run `pnpm generate`, then import from the generated barrel.
import { useGet{Entity}ById, useDelete{Entity} } from '@/hooks/generated/{resources}';
import type { {Entity}, {Entity}Status } from '@repo/validation';
import { ROUTES } from '@/constants/routes';

// ─── Props ────────────────────────────────────────────────────────────────────

interface {Entity}CardProps {
  /** {Entity} ID to fetch and display */
  {entity}Id: string;
  /** Called when user selects this {entity} */
  onSelect?: ({entity}: {Entity}) => void;
  /** Called when {entity} is deleted */
  onDeleted?: (id: string) => void;
}

// ─── Component ────────────────────────────────────────────────────────────────

export function {Entity}Card({ {entity}Id, onSelect, onDeleted }: {Entity}CardProps) {
  const [confirmDelete, setConfirmDelete] = useState(false);

  const { data, isLoading, error } = useGet{Entity}ById({entity}Id);
  const { mutateAsync: delete{Entity}, isPending: isDeleting } = useDelete{Entity}();

  // ─── Handlers ─────────────────────────────────────────────────────────────

  const handleSelect = useCallback(() => {
    if (data) onSelect?.(data);
  }, [data, onSelect]);

  const handleDeleteConfirm = useCallback(async () => {
    if (!data) return;
    await delete{Entity}({ id: data.id });
    setConfirmDelete(false);
    onDeleted?.(data.id);
  }, [data, delete{Entity}, onDeleted]);

  // ─── States ───────────────────────────────────────────────────────────────

  if (isLoading) {
    return (
      <div role="status" aria-label="Loading {entity}" aria-busy="true">
        {/* Replace with a Storybook skeleton component */}
        <span className="sr-only">Loading...</span>
      </div>
    );
  }

  if (error) {
    return (
      <div role="alert" aria-live="assertive">
        <p>Unable to load {entity}. Please try again.</p>
      </div>
    );
  }

  if (!data) return null;

  // ─── Render ───────────────────────────────────────────────────────────────

  return (
    <article aria-labelledby={`{entity}-name-${data.id}`}>
      {/* Card Header */}
      <header>
        <h3 id={`{entity}-name-${data.id}`}>{data.name}</h3>
        <{Entity}StatusBadge status={data.status} />
      </header>

      {/* Card Body */}
      <div>
        <dl>
          <dt>Created by</dt>
          <dd>{data.createdBy}</dd>
          <dt>Created at</dt>
          <dd>
            <time dateTime={data.createdAt}>
              {new Date(data.createdAt).toLocaleDateString('en-AU')}
            </time>
          </dd>
        </dl>
      </div>

      {/* Card Footer — Actions */}
      <footer>
        {/* Navigation — always next/link, never <a href> */}
        <Link href={ROUTES.{ENTITY}_DETAIL(data.id)}>
          View details
          <span className="sr-only"> for {data.name}</span>
        </Link>

        <Button type="button" variant="ghost" onClick={handleSelect} aria-label={`Select ${data.name}`}>
          Select
        </Button>

        <Button
          type="button"
          variant="ghost"
          onClick={() => setConfirmDelete(true)}
          aria-label={`Delete ${data.name}`}
          aria-haspopup="dialog"
        >
          Delete
        </Button>
      </footer>

      {/* Confirm Delete Dialog */}
      {confirmDelete && (
        <div
          role="dialog"
          aria-modal="true"
          aria-labelledby="confirm-delete-title"
          aria-describedby="confirm-delete-desc"
        >
          <h4 id="confirm-delete-title">Confirm Delete</h4>
          <p id="confirm-delete-desc">
            Are you sure you want to delete <strong>{data.name}</strong>? This action cannot be
            undone.
          </p>
          <Button type="button" variant="ghost" onClick={() => setConfirmDelete(false)}>
            Cancel
          </Button>
          <Button
            type="button"
            onClick={handleDeleteConfirm}
            loading={isDeleting}
            aria-busy={isDeleting}
          >
            {isDeleting ? 'Deleting...' : 'Delete'}
          </Button>
        </div>
      )}
    </article>
  );
}

// ─── Sub-components ───────────────────────────────────────────────────────────

interface StatusBadgeProps {
  status: {Entity}Status;
}

function {Entity}StatusBadge({ status }: StatusBadgeProps) {
  const variantMap: Record<{Entity}Status, string> = {
    DRAFT: 'neutral',
    ACTIVE: 'success',
    ARCHIVED: 'warning',
  };

  return (
    <Badge role="status" aria-label={`Status: ${status}`} data-variant={variantMap[status]}>
      {status}
    </Badge>
  );
}
