/**
 * API client for {Entity} service
 * - Zod runtime validation on all responses
 * - Correlation ID on all requests
 * - PingID token attached via shared apiClient interceptor
 */

// Import `z` from @repo/validation (OpenAPI-extended) — NEVER from 'zod' directly.
import { z } from '@repo/validation';
import { apiClient } from '@/lib/api-client';
import type { SearchParams } from '@/types/common';

// ─── Zod Schemas (runtime validation — trust nothing from network) ─────────────

export const { Entity }StatusSchema = z.enum(['DRAFT', 'ACTIVE', 'ARCHIVED']);

export const { Entity }Schema = z.object({
    id: z.string().uuid(),
    name: z.string().min(1).max(200),
    status: { Entity }StatusSchema,
    createdAt: z.string().datetime(),
    createdBy: z.string(),
    updatedAt: z.string().datetime(),
    updatedBy: z.string(),
});

export const { Entity }ListSchema = z.object({
    content: z.array({ Entity }Schema),
    page: z.number().int().min(0),
    size: z.number().int().min(1),
    totalElements: z.number().int(),
    totalPages: z.number().int(),
    first: z.boolean(),
    last: z.boolean(),
});

export const ProblemDetailSchema = z.object({
    type: z.string(),
    title: z.string(),
    status: z.number().int(),
    detail: z.string().optional(),
    instance: z.string().optional(),
    correlationId: z.string(),
    timestamp: z.string().datetime().optional(),
});

// ─── TypeScript Types (inferred from Zod schemas) ─────────────────────────────

export type { Entity } = z.infer < typeof { Entity }Schema >;
export type { Entity }Status = z.infer < typeof { Entity }StatusSchema >;
export type { Entity }List = z.infer < typeof { Entity }ListSchema >;
export type ProblemDetail = z.infer<typeof ProblemDetailSchema>;

// ─── Request Types ────────────────────────────────────────────────────────────

export interface { Entity }SearchParams extends SearchParams {
    status ?: { Entity }Status;
    sortBy ?: keyof Pick<{ Entity }, 'name' | 'createdAt' | 'status'>;
    sortDir ?: 'asc' | 'desc';
}

export interface Create { Entity }Payload {
    name: string;
    // add domain fields
}

export interface Update { Entity }Payload {
    name: string;
    // add domain fields
}

// ─── API Functions ────────────────────────────────────────────────────────────

const BASE = '/api/v1/{resources}';

/**
 * List {entities} with pagination and optional filtering.
 */
export async function get{ Entities } (
    params: { Entity }SearchParams = {}
): Promise<{ Entity }List> {
    const response = await apiClient.get(BASE, { params });
    // Zod parse throws ZodError if shape doesn't match — caught by error boundary
    return { Entity }ListSchema.parse(response.data);
}

/**
 * Get single {entity} by ID.
 */
export async function get{ Entity } ById(id: string): Promise < { Entity } > {
    const response = await apiClient.get(`${BASE}/${id}`);
    return { Entity }Schema.parse(response.data);
}

/**
 * Create a new {entity}.
 * Returns created {entity} with server-assigned ID.
 */
export async function create{ Entity } (
    payload: Create{ Entity }Payload
): Promise<{ Entity }> {
    const response = await apiClient.post(BASE, payload);
    return { Entity }Schema.parse(response.data);
}

/**
 * Update an existing {entity}.
 */
export async function update{ Entity } (
    id: string,
    payload: Update{ Entity }Payload
): Promise<{ Entity }> {
    const response = await apiClient.put(`${BASE}/${id}`, payload);
    return { Entity }Schema.parse(response.data);
}

/**
 * Soft-delete a {entity}.
 */
export async function delete { Entity }(id: string): Promise < void> {
    await apiClient.delete(`${BASE}/${id}`);
}

// ─── Hooks (TanStack Query) — DO NOT HAND-WRITE ───────────────────────────────
//
// STOP: React Query hooks are GENERATED by orval from the OpenAPI spec. Never
// write `useQuery`/`useMutation` by hand — doing so drifts from the contract and
// violates the codegen pipeline (Prisma → Zod → OpenAPI → orval).
//
// To get typed hooks + query keys for {Entity}:
//   1. Ensure the endpoint exists in the Prisma schema / Zod DTOs.
//   2. Run `pnpm generate` (regenerates the spec, hooks, and MSW handlers).
//   3. Import from the generated barrel — e.g.:
//
//      import {
//        useGet{Entities},         // list query hook
//        useGet{Entity}ById,       // detail query hook
//        useCreate{Entity},        // mutation hook
//        useDelete{Entity},        // mutation hook
//        getGet{Entities}QueryKey, // query-key factory for invalidation
//      } from '@/hooks/generated/{resources}';
//
// Query-key factories (getGet…QueryKey) are also generated — use them for
// `queryClient.invalidateQueries({ queryKey: getGet{Entities}QueryKey() })`.
// See @.claude/patterns/orval-codegen-pattern.md and
// @.claude/standards/frontend-standards.md#tanstack-query--orval-relationship.
//
// NOTE: When generated hooks cover an endpoint, the hand-written fetch functions
// above become redundant — prefer the generated client. Keep bespoke fetch
// helpers only for calls the OpenAPI spec cannot express.
